server.port=8081
spring.application.name=task

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
spring.rabbitmq.listener.direct.retry.enabled=true
spring.rabbitmq.listener.direct.retry.initial-interval=1000
spring.rabbitmq.listener.direct.retry.multiplier=2.0
spring.rabbitmq.listener.direct.retry.max-attempts=10